version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/prisma/dev.db:/usr/src/app/dev.db
    environment:
      DATABASE_URL: "file:./dev.db"
    command: sh -c "npx prisma generate && node server.js"

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
