services:
  backend:
    build: 
      context: .
      dockerfile: /backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/usr/src/app/frontend
     - ./backend:/usr/src/app/backend:delegated
     - /usr/src/app/backend/node_modules

    environment:
      DATABASE_URL: "file:./dev.db"  # ou sua URL do PostgreSQL, se for o caso
    command: ["node", "server.js"]
